[project]
name = "gst200b"
version = "1.0.0"
description = "Github for the course GST200B in 2026 W"
readme = "README.md"
requires-python = "==3.14.*"
dependencies = [
    "geopandas>=1.1.2",
    "osmnx>=2.1.0",
    "keplergl>=0.4.0rc4",
    "duckdb>=1.4.3",
    "marimo[sql]>=0.24.2",
    "matplotlib>=3.11.2",
]
