FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    python3 python3-dev python3-venv \
    gdal-bin libgdal-dev \
    nodejs npm \
    build-essential \
    && apt-get clean \
    && rm -rf /var/cache/apk/*

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install --upgrade pip  \
    && pip install --no-cache-dir -r requirements.txt

WORKDIR /jupyter

EXPOSE 8888

# skip the jupyter token 
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''" ]
